@startuml "AWS Sequence Diagram"

title "Shortly - Visualizar URL original"

skinparam participantPadding 35
skinparam style strictuml

!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist

!include AWSPUML/AWSCommon.puml
!include AWSPUML/General/User.puml
!include AWSPUML/Database/RDS.puml
!include AWSPUML/General/Globe.puml
!include AWSPUML/Compute/EC2T3Instance.puml
!include AWSPUML/ManagementGovernance/CloudWatch.puml
!include AWSPUML/ApplicationIntegration/APIGateway.puml

'!include AWSPUML/AWSSimplified.puml

UserParticipant(MyUser, "User", "Cliente")
APIGatewayParticipant(MyApiGateway, "Api Gateway", "Proxy Gateway")
EC2T3InstanceParticipant(MyEC2, "Instância EC2", "NestJS / CodeController@redirectToShortUrl")
RDSParticipant(MyRDS, "Banco de Dados", "Banco de dados relacional MySQL")
CloudWatchParticipant(MyCloudWatch, "Logs do Sistema", "Grupos de Logs")
GlobeParticipant(MyGlobe, "Site Original", "Destino do usuário")

autonumber 1.1
MyUser -> MyApiGateway : GET /v1/code/{code}
autonumber 2.1
MyApiGateway -> MyEC2 : Encaminha a solicitação para o endpoint NestJS apropriado
MyApiGateway -->> MyCloudWatch : Adiciona uma entrada nos logs contendo o RequestID, o método e a rota da solicitação
autonumber 3.1
MyEC2 -> MyRDS : Localiza a URL encurtada pelo seu código
autonumber 3.1
MyRDS --> MyEC2 : Registro ShortUrl da URL encurtada
MyEC2 -->> MyGlobe : HTTP Redirect 301 para o site original

@enduml
