@startuml "AWS Sequence Diagram"

title "Shortly - Encurtamento de URL"

skinparam participantPadding 35
skinparam style strictuml

!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist

!include AWSPUML/AWSCommon.puml
!include AWSPUML/General/User.puml
!include AWSPUML/Database/RDS.puml
!include AWSPUML/Compute/EC2T3Instance.puml
!include AWSPUML/ManagementGovernance/CloudWatch.puml
!include AWSPUML/ApplicationIntegration/APIGateway.puml

'!include AWSPUML/AWSSimplified.puml

UserParticipant(MyUser, "User", "Cliente")
APIGatewayParticipant(MyApiGateway, "Api Gateway", "Proxy Gateway")
EC2T3InstanceParticipant(MyEC2, "Instância EC2", "NestJS / ShortenController@createShortUrl")
RDSParticipant(MyRDS, "Banco de Dados", "Banco de dados relacional MySQL")
CloudWatchParticipant(MyCloudWatch, "Logs do Sistema", "Grupos de Logs")

autonumber 1.1
MyUser -> MyApiGateway : POST /v1/shorten
autonumber 2.1
MyApiGateway -> MyEC2 : Encaminha a solicitação para o endpoint NestJS apropriado
MyApiGateway -->> MyCloudWatch : Adiciona uma entrada nos logs contendo o RequestID, o método e a rota da solicitação
autonumber 3.1
MyEC2 -> MyRDS : Insere o registro ShortUrl da URL encurtada
autonumber 3.1
MyRDS --> MyEC2 : Registro ShortUrl da URL encurtada
autonumber 2.1
MyEC2 --> MyApiGateway : Registro ShortUrl da URL encurtada
autonumber 1.1
MyApiGateway --> MyUser : JSON contendo registro ShortUrl da URL encurtada

@enduml
